### ISSUE TITLE
schema-reader Error: syntax error, unexpected token "return"

### ISSUE THREAD

**Issue by threeel** [VemtoOrg/vemto2-issues#112]
**Error Message:**
schema-reader Error: syntax error, unexpected token "return"

**Stack:**
```
schema-reader Error: #0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/.box/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/threeel/...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\Plan')
#2 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/ModelRepository.php(308): class_exists('App\\Models\\Plan')
#3 [internal function]: Vemto\ModelRepository->Vemto\{closure}(Array, 7)
#4 /Users/threeel/code/blueprintbargain/blueprint-bargain/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(925): array_filter(Array, Object(Closure), 1)
#5 /Users/threeel/code/blueprintbargain/blueprint-bargain/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(387): Illuminate\Support\Arr::where(Array, Object(Closure))
#6 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/ModelRepository.php(305): Illuminate\Support\Collection->filter(Object(Closure))
#7 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/ModelRepository.php(23): Vemto\ModelRepository->get()
#8 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(116): Vemto\ModelRepository->getFormatted()
#9 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#10 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute('schema-reader', Object(Closure))
#11 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#12 {main}

--------

schema-reader Error: #0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/.box/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/threeel/...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Models\\Plan')
#2 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/ModelRepository.php(308): class_exists('App\\Models\\Plan')
#3 [internal function]: Vemto\ModelRepository->Vemto\{closure}(Array, 7)
#4 /Users/threeel/code/blueprintbargain/blueprint-bargain/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(925): array_filter(Array, Object(Closure), 1)
#5 /Users/threeel/code/blueprintbargain/blueprint-bargain/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(387): Illuminate\Support\Arr::where(Array, Object(Closure))
#6 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/ModelRepository.php(305): Illuminate\Support\Collection->filter(Object(Closure))
#7 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/ModelRepository.php(23): Vemto\ModelRepository->get()
#8 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(101): Vemto\ModelRepository->getFormatted()
#9 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#10 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(23): Vemto\Vemto::execute('schema-reader', Object(Closure))
#11 /Applications/Vemto.app/Contents/Resources/static/VMTTL1(15): require('phar:///Applica...')
#12 {main}
```

---

Vemto 2.0.8
darwin 23.4.0
Locale: en-GB
App version: 2.0.8

**Comment by TiagoSilvaPereira** [comment]
Hi @threeel, could you please provide more details?

- Is this a new project or an existing one?
- When does this issue happen?
- Did you check App\\Models\\Plan for syntax errors?

**Comment by threeel** [comment]
hey i am closing it i have found the issue i had a piece of code in a function that was not properly closed.
