### ISSUE TITLE
schema-reader-db Error: Failed opening required 

### ISSUE THREAD

**Issue by vimitali368** [VemtoOrg/vemto2-issues#121]
**How+to+reproduce:**
1. Create a new project:
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/1d868ef4-a16e-4876-b249-6b74f2c360e0)
2. 
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/23ea01eb-6e54-4be2-a799-8038d7560344)
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/a60a18a6-7ba1-4cf5-a266-3cfb3f60f204)
3.Got an error:
![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/99253756/c2648123-c566-4077-a7cc-c2bad76d2290)

schema-reader-db Error: Failed opening required 'D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\bootstrap/../routes/app.php' (include_path='.;D:/.Main/Program/Dev/.Web/Laragon/.Full/.6/etc/php/pear')
schema-reader-db Error: #0 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Routing\Router.php(511): Illuminate\Routing\RouteFileRegistrar->register('D:\\.Main\\Progra...')
#1 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Routing\Router.php(465): Illuminate\Routing\Router->loadRoutes('D:\\.Main\\Progra...')
#2 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Routing\RouteRegistrar.php(194): Illuminate\Routing\Router->group(Array, 'D:\\.Main\\Progra...')
#3 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\bootstrap\app.php(18): Illuminate\Routing\RouteRegistrar->group('D:\\.Main\\Progra...')
#4 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Foundation\Configuration\ApplicationBuilder.php(216): {closure}(Object(Illuminate\Foundation\Application))
#5 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Illuminate\Foundation\Configuration\ApplicationBuilder->Illuminate\Foundation\Configuration\{closure}()
#6 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(81): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#8 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure), Object(Closure))
#9 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Container\Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Object(Closure), Array, NULL)
#10 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(138): Illuminate\Container\Container->call(Object(Closure))
#11 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(52): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#12 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Illuminate\Foundation\Support\Providers\RouteServiceProvider->Illuminate\Foundation\Support\Providers\{closure}()
#13 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(81): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure), Object(Closure))
#16 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Container\Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Object(Closure), Array, NULL)
#17 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php(126): Illuminate\Container\Container->call(Object(Closure))
#18 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1106): Illuminate\Support\ServiceProvider->callBootedCallbacks()
#19 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1084): Illuminate\Foundation\Application->bootProvider(Object(Illuminate\Foundation\Support\Providers\RouteServiceProvider))
#20 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Illuminate\Foundation\Support\Providers\RouteServiceProvider), 41)
#21 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1083): array_walk(Array, Object(Closure))
#22 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#23 D:\.Main\Program\Dev\.Web\Laragon\.Full\.6\www\v209_test1\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(309): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#24 phar://C:/Users/w11.vemto/AppData/Local/Programs/Vemto2/resources/static/VMTTL2/index.php(33): Illuminate\Foundation\Application->bootstrapWith(Array)
#25 phar://C:/Users/w11.vemto/AppData/Local/Programs/Vemto2/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#26 phar://C:/Users/w11.vemto/AppData/Local/Programs/Vemto2/resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#27 C:\Users\w11.vemto\AppData\Local\Programs\Vemto2\resources\static\VMTTL2(14): require('phar://C:/Users...')
#28 {main}

**Comment by vimitali368** [comment]
Vemto 2.0.9
win32 10.0.25262
Locale: ru
App version: 2.0.9

**Comment by vimitali368** [comment]
After installing version 2.0.10, the error went away.
