### ISSUE TITLE
fresh Download Vemto 2.0.2 Pre-Alpha install new laravel 10 project 

### ISSUE THREAD

**Issue by waw3** [VemtoOrg/vemto2-issues#13]
installing...
---
index.3b4255db.js:76 Checking license...
---
index.3b4255db.js:76 Is expired: false
index.3b4255db.js:76 Creating vemto folder
---
index.3b4255db.js:74 has no table User false
---
TypeError: Cannot read properties of null (reading 'forEach')
    at YL.extractLanguageCodesFromLangPaths (index.3b4255db.js:76:104130)
    at YL.getLanguages (index.3b4255db.js:76:104016)
    at async k4e.handle (index.3b4255db.js:76:104326)
    at async L4e.handle (index.3b4255db.js:76:105824)
    at async I4e.generateBasicProjectData (index.3b4255db.js:76:107478)
    at async I4e.connect (index.3b4255db.js:76:106279)
    at async rg.connectProject (index.3b4255db.js:76:108390)
    at async rg.open (index.3b4255db.js:76:108270)
    at async rg.connectFromPath (index.3b4255db.js:76:108095)
    at async y (index.3b4255db.js:76:178910)
---
Database data updated

**Comment by waw3** [comment]
im using MacOS Sonoma 14.3.1

**Comment by TiagoSilvaPereira** [comment]
@waw3 could you please check if this issue still happens on 2.0.4?

**Comment by TiagoSilvaPereira** [comment]
Fixed
