### ISSUE TITLE
schema-reader Error: Class "Livewire\Form" not found

### ISSUE THREAD

**Issue by gtrant** [VemtoOrg/vemto2-issues#15]
**Error Message:**
schema-reader Error: Class "Livewire\Form" not found

**Stack:**
```
schema-reader Error: #0 phar://C:/Users/xxx/AppData/Local/Programs/vemto/resources/static/VMTTL1/.box/vendor/composer/ClassLoader.php(571): include()
#1 phar://C:/Users/xxxx/AppData/Local/Programs/vemto/resources/static/VMTTL1/.box/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('C:\\laragon\\www\\...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Livewire\\Da...')
#3 phar://C:/Users/xxxx/AppData/Local/Programs/vemto/resources/static/VMTTL1/classes/ModelRepository.php(296): class_exists('App\\Livewire\\Da...')
#4 [internal function]: ModelRepository::{closure}(Array, 13)
#5 C:\laragon\www\ve\vemto\vendor\laravel\framework\src\Illuminate\Collections\Arr.php(911): array_filter(Array, Object(Closure), 1)
#6 C:\laragon\www\ve\vemto\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(387): Illuminate\Support\Arr::where(Array, Object(Closure))
#7 phar://C:/Users/xxxx/AppData/Local/Programs/vemto/resources/static/VMTTL1/classes/ModelRepository.php(293): Illuminate\Support\Collection->filter(Object(Closure))
#8 phar://C:/Users/xxxx/AppData/Local/Programs/vemto/resources/static/VMTTL1/classes/ModelRepository.php(15): ModelRepository::getModels()
#9 phar://C:/Users/xxxx/AppData/Local/Programs/vemto/resources/static/VMTTL1/index.php(87): ModelRepository::getModelsFormatted()
#10 phar://C:/Users/xxxx/AppData/Local/Programs/vemto/resources/static/VMTTL1/common/Vemto.php(107): {closure}()
#11 phar://C:/Users/xxxx/AppData/Local/Programs/vemto/resources/static/VMTTL1/index.php(18): Vemto::execute('schema-reader', Object(Closure))
#12 C:\Users\xxxx\AppData\Local\Programs\vemto\resources\static\VMTTL1(14): require('phar://C:/Users...')
#13 {main}
```

---

Vemto 2.0.3
win32 10.0.22631
Locale: en-GB
App version: 2.0.3

**Comment by TiagoSilvaPereira** [comment]
@gtrant Vemto 2 does not install packages yet (I'm working on it). So it is necessary to install Filament manually

**Comment by gtrant** [comment]
all good now
