### ISSUE TITLE
schema-reader-mg Error: Call to a member function compileTables() on null

### ISSUE THREAD

**Issue by jordansitbon** [VemtoOrg/vemto2-issues#152]
Hello,

I'm trying to connect my project on Vemto on an existing App with Laravel 11.9 and Nova 4.34.2

During the connection I get an error message on Vemto :

**Error Message:**
schema-reader-mg Error: Call to a member function compileTables() on null

**Stack:**
```
schema-reader-mg Error: #0 /Users/jordansitbon/Docker/my-project/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(147): Illuminate\Database\Schema\Builder->getTables(false)
#1 /Users/jordansitbon/Docker/my-project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(357): Illuminate\Database\Schema\Builder->hasTable('nova_pending_tr...')
#2 /Users/jordansitbon/Docker/my-project/vendor/laravel/nova/database/migrations/2022_12_19_000000_create_field_attachments_table.php(16): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#3 [internal function]: CreateFieldAttachmentsTable->up()
#4 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/classes/MigrationDecoder.php(22): ReflectionMethod->invoke(Object(CreateFieldAttachmentsTable))
#5 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(98): MigrationDecoder->decode()
#6 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#7 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(23): Vemto\Vemto::execute('schema-reader-m...', Object(Closure))
#8 /Applications/Vemto.app/Contents/Resources/static/VMTTL1(15): require('phar:///Applica...')
#9 {main}
```

If I just ignore the Nova migration I don't have the problem anymore.

NovaServiceProvider.php in `register()`
```php
Nova::ignoreMigrations();
```

But I've seen that Vemto supports Nova in the menus. Even if I don't have access to the interface. Probably not available yet.

---

Vemto 2.0.14
darwin 23.5.0
Locale: fr
App version: 2.0.14

**Comment by TiagoSilvaPereira** [comment]
Hi @jordansitbon for complex or existing projects, it is recommended to use the Database Reader mode. It seems you are using Migrations Reader mode, which is only intended for small prototypes
