### ISSUE TITLE
schema-reader Error: Failed opening required 'phar:///Applications/Vemto.app/Contents/Resources/static/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php8.2.0/lib/php')

### ISSUE THREAD

**Issue by gregvarghese** [VemtoOrg/vemto2-issues#158]
I installed orangehill/iseed to generate a seed for one of my tables and suddenly am getting this error when modifying the schema for another table:

**Error Message:**
schema-reader Error: Failed opening required 'phar:///Applications/Vemto.app/Contents/Resources/static/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php8.2.0/lib/php')

**Stack:**
```
schema-reader Error: #0 schema-reader Error: Failed opening required 'phar:///Applications/Vemto.app/Contents/Resources/static/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php8.2.0/lib/php')
schema-reader Error: #0 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Orangehill\Iseed\IseedServiceProvider->boot()
#1 /vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#2 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#3 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#4 /vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#5 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1103): Illuminate\Container\Container->call(Array)
#6 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1084): Illuminate\Foundation\Application->bootProvider(Object(Orangehill\Iseed\IseedServiceProvider))
#7 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Orangehill\Iseed\IseedServiceProvider), 34)
#8 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1083): array_walk(Array, Object(Closure))
#9 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#10 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(309): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#11 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(41): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#13 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(23): Vemto\Vemto::execute('schema-reader', Object(Closure))
#14 /Applications/Vemto.app/Contents/Resources/static/VMTTL1(15): require('phar:///Applica...')
#15 {main}
```

---

Vemto 2.0.7
darwin 23.5.0
Locale: en-US
App version: 2.0.7

Removing the iseed package allows vemto to work again

**Comment by TiagoSilvaPereira** [comment]
@gregvarghese thanks for reporting, I saw you are using Vemto 2.0.7. Could you please check with Vemto 2.0.14 (latest version)?

**Comment by gregvarghese** [comment]
@TiagoSilvaPereira, I'm sorry. I didn't know there was a new version, as the app hadn't notified me.  I will check today and confirm if it still occurs.

**Comment by TiagoSilvaPereira** [comment]
@gregvarghese perfect! What operating system are you using? Vemto is not updating automatically on macOS, and I still need to solve this bug (I hope to find a solution soon). It is correctly auto-updating on Windows and Linux

**Comment by gregvarghese** [comment]
@TiagoSilvaPereira , MacOS of course 😂

**Comment by TiagoSilvaPereira** [comment]
@gregvarghese I just launched 2.0.15. Could you please test with this version?

**Comment by gregvarghese** [comment]
@TiagoSilvaPereira , I just tested, and the issue seems to be fixed now. I downloaded the newest version, installed iseed, and generated a migration, but Vemto was still running without an error. I'll close the issue now. 

Thanks!
