### ISSUE TITLE
schema-reader-db Error: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'telescope_entries' already exists (Connection: mysql, SQL: create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `batch_id` char(36) not null, `family_hash` varchar(255) null, `should_display_on_index` tinyint(1) not null default '1', `type` varchar(20) not null, `content` longtext not null, `created_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

### ISSUE THREAD

**Issue by juliangums** [VemtoOrg/vemto2-issues#169]
**Error Message:**
schema-reader-db Error: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'telescope_entries' already exists (Connection: mysql, SQL: create table `telescope_entries` (`sequence` bigint unsigned not null auto_increment primary key, `uuid` char(36) not null, `batch_id` char(36) not null, `family_hash` varchar(255) null, `should_display_on_index` tinyint(1) not null default '1', `type` varchar(20) not null, `content` longtext not null, `created_at` datetime null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Stack:**
```
schema-reader-db Error: #0 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Connection.php(767): Illuminate\Database\Connection->runQueryCallback('create table `t...', Array, Object(Closure))
#1 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Connection.php(560): Illuminate\Database\Connection->run('create table `t...', Array, Object(Closure))
#2 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(109): Illuminate\Database\Connection->statement('create table `t...')
#3 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(418): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 <redacted>/database/migrations/2018_08_08_100000_create_telescope_entries_table.php(24): Illuminate\Database\Schema\Builder->create('telescope_entri...', Object(Closure))
#6 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(476): Illuminate\Database\Migrations\Migration@anonymous->up()
#7 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(402): Illuminate\Database\Migrations\Migrator->runMethod(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')
#8 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(411): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#9 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(212): Illuminate\Database\Migrations\Migrator->runMigration(Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')
#10 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(743): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#11 <redacted>/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(212): Illuminate\Database\Migrations\Migrator->write('Illuminate\\Cons...', '2018_08_08_1000...', Object(Closure))
#12 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(179): Illuminate\Database\Migrations\Migrator->runUp('/Users/juliangu...', 1, false)
#13 <redacted>/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(122): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#14 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(114): Illuminate\Database\Migrations\Migrator->run('<redacted>...')
#15 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#16 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#17 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#18 {main}
```

---

Vemto 2.0.21
darwin 23.5.0
Locale: en-GB
App version: 2.0.21

**Comment by TiagoSilvaPereira** [comment]
Hi @juliangums, thank you for reporting. I'll close this as we are already tracking this bug here: #143
