### ISSUE TITLE
Parse Error : syntax error, unexpected '(' on line 33

### ISSUE THREAD

**Issue by navindigi** [VemtoOrg/vemto2-issues#171]
**Error Message:**
Parse Error : syntax error, unexpected '(' on line 33
  31 |         Schema::table('users', function (Blueprint $table) {
  32 |                 $table->bigInteger('id', [])->unsigned()->autoIncrement()->change();
> 33 |                 $table->('first_name', [])->change();
     |                        ^
  34 |                 $table->bigInteger('current_team_id', [])->unsigned()->nullable()->change();
  35 |         });
  36 |     }

**Stack:**
```
SyntaxError: Parse Error : syntax error, unexpected '(' on line 33
  31 |         Schema::table('users', function (Blueprint $table) {
  32 |                 $table->bigInteger('id', [])->unsigned()->autoIncrement()->change();
> 33 |                 $table->('first_name', [])->change();
     |                        ^
  34 |                 $table->bigInteger('current_team_id', [])->unsigned()->nullable()->change();
  35 |         });
  36 |     }
    at vt.raiseError (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.b89c7398.js:286:175)
    at vt.error (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.b89c7398.js:286:830)
    at vt.read_what (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.b89c7398.js:285:8537)
    at vt.recursive_variable_chain_scan (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.b89c7398.js:285:9357)
    at vt.read_variable (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.b89c7398.js:285:7207)
    at vt.read_expr_item (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.b89c7398.js:275:19098)
    at vt.read_expr (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.b89c7398.js:275:12038)
    at vt.read_statement (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.b89c7398.js:285:1944)
    at vt.read_inner_statement (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.b89c7398.js:282:3594)
    at vt.read_inner_statements (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.b89c7398.js:282:2090)
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.21
win32 10.0.22631
Locale: en-US
App version: 2.0.21

**Comment by TiagoSilvaPereira** [comment]
@navindigi It seems you have an invalid column without a type. Please try adding the column type

**Comment by TiagoSilvaPereira** [comment]
@navindigi is this errors still happening on Vemto 2.0.24?

**Comment by TiagoSilvaPereira** [comment]
Please reopen if necessary
