### ISSUE TITLE
schema-reader-db Error: Access to undeclared static property Spatie\Permission\PermissionRegistrar::$pivotPermission

### ISSUE THREAD

**Issue by zerocool-network** [VemtoOrg/vemto2-issues#173]
**Error Message:**
schema-reader-db Error: Access to undeclared static property Spatie\Permission\PermissionRegistrar::$pivotPermission

**Stack:**
```
schema-reader-db Error: #0 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(421): CreatePermissionTables->{closure}(Object(Illuminate\Database\Schema\Blueprint))
#1 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Support/helpers.php(365): Illuminate\Database\Schema\Builder->Illuminate\Database\Schema\{closure}(Object(Illuminate\Database\Schema\Blueprint))
#2 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(418): tap(Object(Illuminate\Database\Schema\Blueprint), Object(Closure))
#3 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(357): Illuminate\Database\Schema\Builder->create('model_has_permi...', Object(Closure))
#4 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/database/migrations/2023_05_08_103315_create_permission_tables.php(53): Illuminate\Support\Facades\Facade::__callStatic('create', Array)
#5 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(476): CreatePermissionTables->up()
#6 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(402): Illuminate\Database\Migrations\Migrator->runMethod(Object(Illuminate\Database\MySqlConnection), Object(CreatePermissionTables), 'up')
#7 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(411): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#8 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(212): Illuminate\Database\Migrations\Migrator->runMigration(Object(CreatePermissionTables), 'up')
#9 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(743): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#10 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(212): Illuminate\Database\Migrations\Migrator->write('Illuminate\\Cons...', '2023_05_08_1033...', Object(Closure))
#11 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(179): Illuminate\Database\Migrations\Migrator->runUp('/Volumes/zeroco...', 1, false)
#12 /Volumes/zerocool/Backup/Proyectos/Clientes/Expansiva/expansiva_2/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(122): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#13 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(114): Illuminate\Database\Migrations\Migrator->run('/Volumes/zeroco...')
#14 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#15 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#16 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#17 {main}
```

---

Vemto 2.0.23
darwin 23.5.0
Locale: es
App version: 2.0.23

**Comment by TiagoSilvaPereira** [comment]
Hi, @zerocool-network. It seems to be a project-related issue. Are your project migrations running correctly?

**Comment by zerocool-network** [comment]
I'm sorry, there was a mistake in my structure, I've already solved it.
