### ISSUE TITLE
schema-reader-db Error: DB connection failed: SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by abnersobrinho** [VemtoOrg/vemto2-issues#176]
**Error Message:**
schema-reader-db Error: DB connection failed: SQLSTATE[HY000] [2002] Connection refused

**Stack:**
```
schema-reader-db Error: #0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/src/DatabaseManager.php(20): VemtoDBReader\DatabaseManager->connect()
#1 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(94): VemtoDBReader\DatabaseManager->__construct('mysql')
#2 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#3 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#4 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#5 {main}
```

---

Vemto 2.0.23
darwin 23.5.0
Locale: pt-BR
App version: 2.0.23

**Comment by TiagoSilvaPereira** [comment]
Hi @abnersobrinho Could you please check if your connection settings are valid?

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/fdd26759-e665-47e3-a4c5-06bbd8c9ec9b)

**Comment by TiagoSilvaPereira** [comment]
@abnersobrinho does restarting mysql service or closing Vemto and opening it again solves this issue?

**Comment by TiagoSilvaPereira** [comment]
Closing due to inactivity. Please feel free to continue the discussion
