### ISSUE TITLE
schema-reader-db Error: DB connection failed: could not find driver

### ISSUE THREAD

**Issue by Parkbyounghyo** [VemtoOrg/vemto2-issues#179]
**Error Message:**
schema-reader-db Error: DB connection failed: could not find driver

**Stack:**
```
schema-reader-db Error: #0 phar://C:/Program Files/Vemto/resources/static/VMTTL2/src/DatabaseManager.php(20): VemtoDBReader\DatabaseManager->connect()
#1 phar://C:/Program Files/Vemto/resources/static/VMTTL2/index.php(94): VemtoDBReader\DatabaseManager->__construct('mariadb')
#2 phar://C:/Program Files/Vemto/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#3 phar://C:/Program Files/Vemto/resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#4 C:\Program Files\Vemto\resources\static\VMTTL2(14): require('phar://C:/Progr...')
#5 {main}
```

---

Vemto 2.0.23
win32 10.0.19045
Locale: ko
App version: 2.0.23

**Comment by Parkbyounghyo** [comment]
테스트해보니 maria 디비 연결이 문제인거 같습니다. 
mysql은 정상적으로 접속됩니다.

**Comment by TiagoSilvaPereira** [comment]
@Parkbyounghyo is mariadb extension enabled on your PHP installation?

**Comment by TiagoSilvaPereira** [comment]
@Parkbyounghyo did you manage to check this?

**Comment by TiagoSilvaPereira** [comment]
Closing for now, please feel free to reopen if necessary
