### ISSUE TITLE
this.default.replace is not a function

### ISSUE THREAD

**Issue by inbonizey** [VemtoOrg/vemto2-issues#188]
**Error Message:**
![error](https://github.com/user-attachments/assets/db78eec3-0588-4ceb-bd65-013a35a14b2d)

this.default.replace is not a function

**Stack:**
```
TypeError: this.default.replace is not a function
    at Proxy.getDefaultForTemplate (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.eb54a06c.js:115:63131)
    at Object.eval (eval at compileAsync (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.eb54a06c.js:320:649), <anonymous>:588:25)
    at Iae.compileAsync (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.eb54a06c.js:320:675)
    at Iae.compileAsyncWithErrorTreatment (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.eb54a06c.js:320:290)
    at jy.compile (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.eb54a06c.js:366:14378)
    at jy.compileWithImports (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.eb54a06c.js:366:13975)
    at async Upe.generateUpdaterMigration (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.eb54a06c.js:1160:146504)
    at async Upe.getContent (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.eb54a06c.js:1160:145570)
    at async Upe.getData (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.eb54a06c.js:1160:144499)
    at async as (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.eb54a06c.js:1274:14423)
```

**Template Name:**
```
(anonymous template)
```

**Template Error Line:**
```
420
```

**Template Section:**
```js
418                    <# --- #>
419                    <up if (column.default) { up>
420                    ->default(<$ column.getDefaultForTemplate() $>)
421                    <up } up>
422                    <# --- #>
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.1.2
win32 10.0.19045
Locale: fr
App version: 2.1.2

**Comment by TiagoSilvaPereira** [comment]
@inbonizey thanks, I'll check this. Could you please show me how to reproduce?

**Comment by TiagoSilvaPereira** [comment]
@inbonizey please check 2.1.3

**Comment by inbonizey** [comment]
Great !
Resolved
