### ISSUE TITLE
schema-reader-db Error: Class "Redis" not found

### ISSUE THREAD

**Issue by FdClemente** [VemtoOrg/vemto2-issues#189]
**Error Message:**
schema-reader-db Error: Class "Redis" not found

Laravel app with sail

**Stack:**
```
schema-reader-db Error: #0 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(33): Illuminate\Redis\Connectors\PhpRedisConnector->createClient(Array)
#1 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(38): Illuminate\Redis\Connectors\PhpRedisConnector->Illuminate\Redis\Connectors\{closure}()
#2 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(110): Illuminate\Redis\Connectors\PhpRedisConnector->connect(Array, Array)
#3 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(91): Illuminate\Redis\RedisManager->resolve('cache')
#4 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(330): Illuminate\Redis\RedisManager->connection('cache')
#5 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(65): Illuminate\Cache\RedisStore->connection()
#6 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(107): Illuminate\Cache\RedisStore->get('telescope:dump-...')
#7 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(440): Illuminate\Cache\Repository->get('telescope:dump-...')
#8 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/telescope/src/Watchers/DumpWatcher.php(47): Illuminate\Cache\CacheManager->__call('get', Array)
#9 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/telescope/src/RegistersWatchers.php(48): Laravel\Telescope\Watchers\DumpWatcher->register(Object(Illuminate\Foundation\Application))
#10 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/telescope/src/Telescope.php(135): Laravel\Telescope\Telescope::registerWatchers(Object(Illuminate\Foundation\Application))
#11 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/telescope/src/TelescopeServiceProvider.php(33): Laravel\Telescope\Telescope::start(Object(Illuminate\Foundation\Application))
#12 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Telescope\TelescopeServiceProvider->boot()
#13 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1114): Illuminate\Container\Container->call(Array)
#18 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1095): Illuminate\Foundation\Application->bootProvider(Object(Laravel\Telescope\TelescopeServiceProvider))
#19 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Laravel\Telescope\TelescopeServiceProvider), 'Laravel\\Telesco...')
#20 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1094): array_walk(Array, Object(Closure))
#21 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#22 /Users/filipeclemente/projetos/freelas/RWI/timetrackerPro/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#23 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(39): Illuminate\Foundation\Application->bootstrapWith(Array)
#24 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#25 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#26 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#27 {main}
```

---

Vemto 2.1.3
darwin 24.0.0
Locale: pt-PT
App version: 2.1.3

**Comment by TiagoSilvaPereira** [comment]
@fdc2001 is this a new project created with Vemto? Or an existing project? Is Redis correctly installed?

**Comment by FdClemente** [comment]
Hi @TiagoSilvaPereira,
This a existing project, I have created with laravel.build. Everything work perfectly, but on open project with vemto show this error.

**Comment by TiagoSilvaPereira** [comment]
@fdc2001 it seems Redis is not installed in the project yet (Vemto needs to boot the Laravel application, so if some requirement is missing, it can't start). Please check if this helps:

https://stackoverflow.com/questions/70075845/class-redis-not-found-laravel-8-using-phpredis

Could you also check if creating a new application from Vemto fires this error, please?

**Comment by TiagoSilvaPereira** [comment]
Hi @fdc2001 did you try the link above? Could you please check if this works with a new project?
