### ISSUE TITLE
schema-reader-mg Error: Call to a member function bootstrapWith() on int

### ISSUE THREAD

**Issue by steven-maina** [VemtoOrg/vemto2-issues#190]
**Error Message:**
schema-reader-mg Error: Call to a member function bootstrapWith() on int

**Stack:**
```
schema-reader-mg Error: #0 phar://C:/Program Files/Vemto/resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#1 phar://C:/Program Files/Vemto/resources/static/VMTTL1/index.php(25): Vemto\Vemto::execute('schema-reader-m...', Object(Closure))
#2 C:\Program Files\Vemto\resources\static\VMTTL1(14): require('phar://C:/Progr...')
#3 {main}
```

---

Vemto 2.1.3
win32 10.0.19045
Locale: en-US
App version: 2.1.3

**Comment by TiagoSilvaPereira** [comment]
@steven-maina is this a new project created with Vemto. Or an existing one?

**Comment by steven-maina** [comment]
Created vemto project then yesterday i tried to open it i was getting that
error
Deleted vendor folder and all vemto files and folder
When i try now to import i don't get the error but now the project isn't
opening in Vemto

**Comment by TiagoSilvaPereira** [comment]
@steven-maina, could you please try creating a new project and check if the same error happens?
