### ISSUE TITLE
schema-reader-mg Error: Class "Laravel\Pulse\Support\PulseMigration" not found

### ISSUE THREAD

**Issue by GregsGrog** [VemtoOrg/vemto2-issues#192]
**Error Message:**
schema-reader-mg Error: Class "Laravel\Pulse\Support\PulseMigration" not found

**Stack:**
```
schema-reader-mg Error: #0 C:\laragon\www\HomeHub\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(123): require()
#1 C:\laragon\www\HomeHub\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(124): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#2 C:\laragon\www\HomeHub\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(508): Illuminate\Filesystem\Filesystem->getRequire('C:\\laragon\\www\\...')
#3 phar://C:/Users/tom/AppData/Local/Programs/Vemto/resources/static/VMTTL1/classes/ExtendedMigrator.php(10): Illuminate\Database\Migrations\Migrator->resolvePath('C:\\laragon\\www\\...')
#4 phar://C:/Users/tom/AppData/Local/Programs/Vemto/resources/static/VMTTL1/index.php(95): ExtendedMigrator->resolveMigrationPath('C:\\laragon\\www\\...')
#5 phar://C:/Users/tom/AppData/Local/Programs/Vemto/resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#6 phar://C:/Users/tom/AppData/Local/Programs/Vemto/resources/static/VMTTL1/index.php(25): Vemto\Vemto::execute('schema-reader-m...', Object(Closure))
#7 C:\Users\tom\AppData\Local\Programs\Vemto\resources\static\VMTTL1(14): require('phar://C:/Users...')
#8 {main}
```

---

Vemto 2.1.3
win32 10.0.22631
Locale: en-US
App version: 2.1.3

**Comment by GregsGrog** [comment]
Unsure why its screaming about pulse when that hasnt ever been installed in this project as far as I can remember.

**Comment by TiagoSilvaPereira** [comment]
@GregsGrog is this a new project or an existing one? Vemto tries to boot the application to read the migrations. Something is missing in the application /vendor folder if this error occurs. What happens if you try to run an artisan command? For example php artisan route:list?

**Comment by GregsGrog** [comment]
Its an existing project but all artisan commands work just fine the project is running with no issues other than the one described by Vemto. Running php artisan route:list shows the route list as usual. Sorry if that isnt much help.

**Comment by TiagoSilvaPereira** [comment]
@GregsGrog, thanks. Could you please try to reproduce this error with a new project and give the instructions on how to reproduce the problem here?

**Comment by TiagoSilvaPereira** [comment]
Tested on 2.1.10 and seems pulse is working well. Please feel free to add more details if necessary. Closing for now
