### ISSUE TITLE
SQL Server - An invalid keyword 'host' was specified in the DSN string.

### ISSUE THREAD

**Issue by art35rennes** [VemtoOrg/vemto2-issues#196]
I try a create a project that connect to a SQL Server to build migration files. Connection values works well on DataGrip, i can connect to server.

I use IP as host, set port to 1433 (MSSQL default).

Error look to be raised because `host` parameter is used instead of `server`
 [PHP-PDO error: An invalid keyword 'host' was specified in the DSN string](https://stackoverflow.com/questions/32213104/php-pdo-error-an-invalid-keyword-host-was-specified-in-the-dsn-string)

**Error Message:**
schema-reader-db Error: DB connection failed: SQLSTATE[IMSSP]: An invalid keyword 'host' was specified in the DSN string.

**Stack:**
```
schema-reader-db Error: #0 phar://C:/Program Files/Vemto/resources/static/VMTTL2/src/DatabaseManager.php(20): VemtoDBReader\DatabaseManager->connect()
#1 phar://C:/Program Files/Vemto/resources/static/VMTTL2/index.php(94): VemtoDBReader\DatabaseManager->__construct()
#2 phar://C:/Program Files/Vemto/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#3 phar://C:/Program Files/Vemto/resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute()
#4 C:\Program Files\Vemto\resources\static\VMTTL2(14): require('...')
#5 {main}
```

---

Vemto 2.1.3
win32 10.0.22621
Locale: fr
App version: 2.1.3

**Comment by TiagoSilvaPereira** [comment]
Hi @art35rennes thank you for reporting, we'll check this

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.1.13
