### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by shahabzebare** [VemtoOrg/vemto2-issues#197]
**Error Message:**
Cannot read properties of undefined (reading 'toLowerCase')

**Stack:**
```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at sLt.isReserved (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.de5826e7.js:1160:131402)
    at b (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.de5826e7.js:1160:134646)
    at y (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.de5826e7.js:1160:134490)
    at file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.de5826e7.js:1160:139845
    at Sc.t.<computed>.t.<computed> (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.de5826e7.js:28:17976)
    at Zv (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.de5826e7.js:16:2031)
    at Ip (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.de5826e7.js:16:2102)
    at HTMLDivElement.t (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.de5826e7.js:28:8321)
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.1.3
darwin 23.6.0
Locale: en-US
App version: 2.1.3

**Comment by TiagoSilvaPereira** [comment]
Hi @shahabzebare just fixed this on 2.1.4
