### ISSUE TITLE
schema-reader-mg Error: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (Connection: mysql, SQL: delete from `cache` where `key` in ())

### ISSUE THREAD

**Issue by cwethm** [VemtoOrg/vemto2-issues#199]
**Error Message:**
schema-reader-mg Error: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (Connection: mysql, SQL: delete from `cache` where `key` in ())

**Stack:**
```
schema-reader-mg Error: #0 /home/cweth/Documents/laravel/Sten5Base/vendor/laravel/framework/src/Illuminate/Database/Connection.php(779): Illuminate\Database\Connection->runQueryCallback()
#1 /home/cweth/Documents/laravel/Sten5Base/vendor/laravel/framework/src/Illuminate/Database/Connection.php(584): Illuminate\Database\Connection->run()
#2 /home/cweth/Documents/laravel/Sten5Base/vendor/laravel/framework/src/Illuminate/Database/Connection.php(548): Illuminate\Database\Connection->affectingStatement()
#3 /home/cweth/Documents/laravel/Sten5Base/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(4017): Illuminate\Database\Connection->delete()
#4 /home/cweth/Documents/laravel/Sten5Base/vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php(383): Illuminate\Database\Query\Builder->delete()
#5 /home/cweth/Documents/laravel/Sten5Base/vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php(359): Illuminate\Cache\DatabaseStore->forgetMany()
#6 /home/cweth/Documents/laravel/Sten5Base/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(484): Illuminate\Cache\DatabaseStore->forget()
#7 /home/cweth/Documents/laravel/Sten5Base/database/migrations/2024_08_23_115921_create_permission_tables.php(120): Illuminate\Cache\Repository->forget()
#8 [internal function]: Illuminate\Database\Migrations\Migration@anonymous->up()
#9 phar:///home/cweth/Documents/laravel/squashfs-root/resources/static/VMTTL1/classes/MigrationDecoder.php(22): ReflectionMethod->invoke()
#10 phar:///home/cweth/Documents/laravel/squashfs-root/resources/static/VMTTL1/index.php(100): MigrationDecoder->decode()
#11 phar:///home/cweth/Documents/laravel/squashfs-root/resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#12 phar:///home/cweth/Documents/laravel/squashfs-root/resources/static/VMTTL1/index.php(25): Vemto\Vemto::execute()
#13 /home/cweth/Documents/laravel/squashfs-root/resources/static/VMTTL1(15): require('...')
#14 {main}
```

---

Vemto 2.1.4
linux 6.8.0-41-generic
Locale: en-US
App version: 2.1.4

**Comment by TiagoSilvaPereira** [comment]
Hi @cwethm, it seems like there is a database authorization issue. Please check the database connection settings
