### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by tjaoc** [VemtoOrg/vemto2-issues#201]
**Error Message:**
Cannot read properties of undefined (reading 'replace')

**Stack:**
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at /Applications/Vemto.app/Contents/Resources/app.asar/build/src/main/main.js:46:8039
    at Array.forEach (<anonymous>)
    at hR.parse (/Applications/Vemto.app/Contents/Resources/app.asar/build/src/main/main.js:46:7917)
    at hR.setContent (/Applications/Vemto.app/Contents/Resources/app.asar/build/src/main/main.js:46:6779)
    at new hR (/Applications/Vemto.app/Contents/Resources/app.asar/build/src/main/main.js:46:6705)
    at dR.<anonymous> (/Applications/Vemto.app/Contents/Resources/app.asar/build/src/main/main.js:50:1788)
    at Generator.next (<anonymous>)
    at /Applications/Vemto.app/Contents/Resources/app.asar/build/src/main/main.js:50:1580
    at new Promise (<anonymous>)
    at cR (/Applications/Vemto.app/Contents/Resources/app.asar/build/src/main/main.js:50:1400)
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.1.5
darwin 23.6.0
Locale: pt-PT
App version: 2.1.5

**Comment by TiagoSilvaPereira** [comment]
Hi @tjaoc is this a new project? How can I reproduce this bug?

**Comment by TiagoSilvaPereira** [comment]
@tjaoc I already identified the problem, the fix is coming in the next version. Thanks
