### ISSUE TITLE
Cannot read properties of null (reading 'show')

### ISSUE THREAD

**Issue by theolundqvist** [VemtoOrg/vemto2-issues#202]
**Error Message:**
Cannot read properties of null (reading 'show')

**Stack:**
```
TypeError: Cannot read properties of null (reading 'show')
    at window.showLicenseModal (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.0a2a41c3.js:410:7922)
    at I (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.0a2a41c3.js:410:9123)
    at A (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.0a2a41c3.js:410:9044)
    at T (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.0a2a41c3.js:410:8403)
    at e.value.te.projectIsReady.k.onClick.Le.<computed>.Le.<computed> (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.0a2a41c3.js:410:12131)
    at Zv (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.0a2a41c3.js:16:2031)
    at Np (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.0a2a41c3.js:16:2102)
    at HTMLButtonElement.t (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.0a2a41c3.js:28:8321)
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.1.5
darwin 23.5.0
Locale: en-GB
App version: 2.1.5

**Comment by alkalmimelos** [comment]
Hi,

I got same error message when I created new table in Schema Editor. 
This is the new project. I make a new table with some columns, save the changes, then when I click generate code I got this message.

**Comment by alkalmimelos** [comment]
I downgrade to 2.0.7. I don't get "Cannot read properties of null" error message in this version, but I get another message: "This project has more than 15 tables (including Laravel default tables). Please activate your license to generate code." If I look around I count 8 table in my schema + 1 in Laravel schema, what it I don't see?

**Comment by TiagoSilvaPereira** [comment]
@theolundqvist @alkalmimelos Sorry for that. Please upgrade to 2.1.6, and this problem will be fixed.

@alkalmimelos there are 7 tables in the Laravel section (they are stacked together but soon I'll launch a version with those tables in different positions in the screen). Also, I pretend not to take those Laravel tables into account in the upcoming versions.

https://github.com/user-attachments/assets/64cfd3d9-cf62-43a3-8b56-f7b4925415fc
