### ISSUE TITLE
Invalid argument expected string

### ISSUE THREAD

**Issue by AleDev11** [VemtoOrg/vemto2-issues#204]
**Error Message:**
Invalid argument expected string

**Stack:**
```
TypeError: Invalid argument expected string
    at AK (file:///C:/Users/fonta/AppData/Local/Programs/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:112:21508)
    at px (file:///C:/Users/fonta/AppData/Local/Programs/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:112:22050)
    at DVe.isPhpVersionValid (file:///C:/Users/fonta/AppData/Local/Programs/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:360:1898)
    at DVe.allDependenciesAreValid (file:///C:/Users/fonta/AppData/Local/Programs/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:360:2162)
    at DVe.hasMissingDependencies (file:///C:/Users/fonta/AppData/Local/Programs/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:360:2098)
    at r (file:///C:/Users/fonta/AppData/Local/Programs/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:360:5049)
```

---

Vemto 2.1.6
win32 10.0.22631
Locale: es
App version: 2.1.6

**Comment by TiagoSilvaPereira** [comment]
Hi @AleDev11, thank you for reporting. Could you please share how I can reproduce this issue?

**Comment by AleDev11** [comment]
Of course, the problem occurred when I put only the php.exe path and left the other option empty.

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.1.13
