### ISSUE TITLE
schema-reader-db Error: Failed opening required '/Users/veresimre/Herd/ekaer/bootstrap/../routes/app.php' (include_path='.:')

### ISSUE THREAD

**Issue by vimre** [VemtoOrg/vemto2-issues#205]
Hi,

It seems latest version of Vemto has some problem opening folders and files on Mac (Herd project).

**Error Message:**
schema-reader-db Error: Failed opening required '/Users/veresimre/Herd/ekaer/bootstrap/../routes/app.php' (include_path='.:')

**Stack:**
```
schema-reader-db Error: #0 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): Illuminate\Routing\RouteFileRegistrar->register('/Users/veresimr...')
#1 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(467): Illuminate\Routing\Router->loadRoutes('/Users/veresimr...')
#2 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php(194): Illuminate\Routing\Router->group(Array, '/Users/veresimr...')
#3 /Users/veresimre/Herd/ekaer/bootstrap/app.php(18): Illuminate\Routing\RouteRegistrar->group('/Users/veresimr...')
#4 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Foundation/Configuration/ApplicationBuilder.php(232): {closure}(Object(Illuminate\Foundation\Application))
#5 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Foundation\Configuration\ApplicationBuilder->Illuminate\Foundation\Configuration\{closure}()
#6 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(83): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#8 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure), Object(Closure))
#9 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Object(Closure), Array, NULL)
#10 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(162): Illuminate\Container\Container->call(Object(Closure))
#11 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(59): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#12 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Foundation\Support\Providers\RouteServiceProvider->Illuminate\Foundation\Support\Providers\{closure}()
#13 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(83): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure), Object(Closure))
#16 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Object(Closure), Array, NULL)
#17 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(130): Illuminate\Container\Container->call(Object(Closure))
#18 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1122): Illuminate\Support\ServiceProvider->callBootedCallbacks()
#19 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1100): Illuminate\Foundation\Application->bootProvider(Object(Illuminate\Foundation\Support\Providers\RouteServiceProvider))
#20 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Illuminate\Foundation\Support\Providers\RouteServiceProvider), 'Illuminate\\Foun...')
#21 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1099): array_walk(Array, Object(Closure))
#22 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#23 /Users/veresimre/Herd/ekaer/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(316): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#24 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(39): Illuminate\Foundation\Application->bootstrapWith(Array)
#25 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#26 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#27 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#28 {main}
```

---

Vemto 2.1.6
darwin 23.6.0
Locale: hu
App version: 2.1.6

**Comment by TiagoSilvaPereira** [comment]
Hi @vimre thank you for reporting, I think this is related to: https://github.com/TiagoSilvaPereira/vemto2-issues/issues/200

The problem was already fixed, but if your project was created with 2.1.4 or 2.1.5, you might have some issues (I explain how to solve them in the link above)

**Comment by TiagoSilvaPereira** [comment]
Closing, please feel free to reopen if necessary
