### ISSUE TITLE
schema-reader-db Error: Call to undefined method Illuminate\Database\Schema\MySqlBuilder::getTableListing()

### ISSUE THREAD

**Issue by RanaMoizHaider** [VemtoOrg/vemto2-issues#208]
**Error Message:**
schema-reader-db Error: Call to undefined method Illuminate\Database\Schema\MySqlBuilder::getTableListing()

**Stack:**
```
schema-reader-db Error: #0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/vendor/kitloong/laravel-migrations-generator/src/Database/DatabaseSchema.php(69): Illuminate\Support\Facades\Facade::__callStatic('getTableListing', Array)
#1 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/src/ReadTablesFromDatabase.php(55): KitLoong\MigrationsGenerator\Database\DatabaseSchema->getTableNames()
#2 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(120): VemtoDBReader\ReadTablesFromDatabase->handle()
#3 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#4 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#5 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#6 {main}
```

---

Vemto 2.1.6
darwin 24.0.0
Locale: en-GB
App version: 2.1.6

**Comment by TiagoSilvaPereira** [comment]
Hi @RanaMoizHaider is this a new project or an existing one?

**Comment by RanaMoizHaider** [comment]
Existing one

**Comment by TiagoSilvaPereira** [comment]
Could you please check if this error happens with a new Laravel project?

**Comment by RanaMoizHaider** [comment]
Checked. No error with a new Laravel project.

**Comment by TiagoSilvaPereira** [comment]
@TiagoSilvaPereira, sorry for the long wait. Your last comment was on the day my son was born, and I forgot to answer you. Could you please check if this works with Vemto 2.1.10? thanks

**Comment by TiagoSilvaPereira** [comment]
Closing as this was probably fixed on recent versions.
