### ISSUE TITLE
schema-reader-mg Error: Call to a member function compileTables() on null

### ISSUE THREAD

**Issue by kellvembarbosa** [VemtoOrg/vemto2-issues#209]
**Error Message:**
schema-reader-mg Error: Call to a member function compileTables() on null

**Stack:**
```
schema-reader-mg Error: #0 /Users/kellvembarbosa/Documents/vemto-test/dogdot-backend/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(148): Illuminate\Database\Schema\Builder->getTables(false)
#1 /Users/kellvembarbosa/Documents/vemto-test/dogdot-backend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(357): Illuminate\Database\Schema\Builder->hasTable('nova_pending_tr...')
#2 /Users/kellvembarbosa/Documents/vemto-test/dogdot-backend/vendor/laravel/nova/database/migrations/2022_12_19_000000_create_field_attachments_table.php(16): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#3 [internal function]: CreateFieldAttachmentsTable->up()
#4 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/classes/MigrationDecoder.php(22): ReflectionMethod->invoke(Object(CreateFieldAttachmentsTable))
#5 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(100): MigrationDecoder->decode()
#6 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#7 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(25): Vemto\Vemto::execute('schema-reader-m...', Object(Closure))
#8 /Applications/Vemto.app/Contents/Resources/static/VMTTL1(15): require('phar:///Applica...')
#9 {main}
```

---

Vemto 2.1.6
darwin 23.4.0
Locale: pt-BR
App version: 2.1.6

**Comment by TiagoSilvaPereira** [comment]
Hi @kellvembarbosa please try Database Reader mode (it seems your migrations have specific database logic)
