### ISSUE TITLE
Item with identifier 678 not found on table relationships

### ISSUE THREAD

**Issue by alexfleites** [VemtoOrg/vemto2-issues#21]
**Error Message:**
Item with identifier 678 not found on table relationships

**Stack:**
```
Error: Item with identifier 678 not found on table relationships
    at $h.findOrFail (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.b25c3afb.js:63:2487)
    at Proxy.fresh (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.b25c3afb.js:63:24075)
    at Proxy.update (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.b25c3afb.js:63:25360)
    at Proxy.save (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.b25c3afb.js:63:25094)
    at b4e.fillRelationship (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.b25c3afb.js:89:26035)
    at Proxy.fillRelationshipKeys (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.b25c3afb.js:89:37784)
    at file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.b25c3afb.js:92:90980
    at Array.forEach (<anonymous>)
    at T2.setRelatedModels (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.b25c3afb.js:92:90909)
    at T2.processModels (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.b25c3afb.js:92:89534)
```

---

Vemto 2.0.4
darwin 23.2.0
Locale: en-US
App version: 2.0.4

**Comment by TiagoSilvaPereira** [comment]
Hi @alexfleites when this error happens? Could you please explain how I can reproduce this error?

**Comment by alexfleites** [comment]
Easy, I am only connect to filament project, then start creating my schema, click Save and stuck in this errors.

Let me know if you need a video or something.



Alexander Fleites
w: https://github.com/fcdeveloper 
 

CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by TiagoSilvaPereira** [comment]
Yes, please... also, could you please try with a new project and check if this still happens?

**Comment by alexfleites** [comment]
￼



Alexander Fleites
w: https://github.com/fcdeveloper 
 

CONFIDENTIALITY NOTICE: The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by TiagoSilvaPereira** [comment]
Hi @alexfleites, sorry, the message came empty

**Comment by TiagoSilvaPereira** [comment]
Closing due to inactivity
