### ISSUE TITLE
schema-reader-db Error: DB connection failed: SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by Odilbukh** [VemtoOrg/vemto2-issues#211]
**Error Message:**
schema-reader-db Error: DB connection failed: SQLSTATE[HY000] [2002] No such file or directory

**Stack:**
```
schema-reader-db Error: #0 phar:///tmp/.mount_Vemto-kNGqyq/resources/static/VMTTL2/src/DatabaseManager.php(20): VemtoDBReader\DatabaseManager->connect()
#1 phar:///tmp/.mount_Vemto-kNGqyq/resources/static/VMTTL2/index.php(94): VemtoDBReader\DatabaseManager->__construct()
#2 phar:///tmp/.mount_Vemto-kNGqyq/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#3 phar:///tmp/.mount_Vemto-kNGqyq/resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute()
#4 /tmp/.mount_Vemto-kNGqyq/resources/static/VMTTL2(15): require('...')
#5 {main}
```

---

Vemto 2.1.6
linux 6.8.0-45-generic
Locale: en-US
App version: 2.1.6

**Comment by TiagoSilvaPereira** [comment]
Closing as this is generally related to the MySQL server not running. Not related to Vemto
