### ISSUE TITLE
schema-reader-db Error: SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined (Connection: vemto_db_connection, SQL: alter table `posts` add primary key (`id`))

### ISSUE THREAD

**Issue by Bychrist** [VemtoOrg/vemto2-issues#213]
**Error Message:**
schema-reader-db Error: SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined (Connection: vemto_db_connection, SQL: alter table `posts` add primary key (`id`))

**Stack:**
```
schema-reader-db Error: #0 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Connection.php(779): Illuminate\Database\Connection->runQueryCallback('alter table `po...', Array, Object(Closure))
#1 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Connection.php(560): Illuminate\Database\Connection->run('alter table `po...', Array, Object(Closure))
#2 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php(117): Illuminate\Database\Connection->statement('alter table `po...')
#3 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(564): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(406): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(358): Illuminate\Database\Schema\Builder->table('posts', Object(Closure))
#6 C:\xampp\htdocs\Vemtotest\GabbyFilament\database\migrations\2024_11_02_141755_001_update_posts_table.php(15): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#7 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(475): Illuminate\Database\Migrations\Migration@anonymous->up()
#8 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(400): Illuminate\Database\Migrations\Migrator->runMethod(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')
#9 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(409): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#10 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(212): Illuminate\Database\Migrations\Migrator->runMigration(Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')
#11 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(740): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#12 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(212): Illuminate\Database\Migrations\Migrator->write('Illuminate\\Cons...', '2024_11_02_1417...', Object(Closure))
#13 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(179): Illuminate\Database\Migrations\Migrator->runUp('C:\\xampp\\htdocs...', 1, false)
#14 C:\xampp\htdocs\Vemtotest\GabbyFilament\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(122): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#15 phar://C:/Program Files/Vemto/resources/static/VMTTL2/index.php(117): Illuminate\Database\Migrations\Migrator->run('C:\\xampp\\htdocs...')
#16 phar://C:/Program Files/Vemto/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#17 phar://C:/Program Files/Vemto/resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#18 C:\Program Files\Vemto\resources\static\VMTTL2(14): require('phar://C:/Progr...')
#19 {main}
```

---

Vemto 2.1.6
win32 10.0.19045
Locale: en-US
App version: 2.1.6

**Comment by TiagoSilvaPereira** [comment]
Hi @Bychrist is this a new project? Or an existing project? Could you please share more details?

**Comment by TiagoSilvaPereira** [comment]
Hi @Bychrist it seems you have defined multiple PKs indexes for a single table. You can check this in the Index section of a table. I'm closing as this seems not to be a Vemto bug, but please feel free to reopen if necessary
