### ISSUE TITLE
schema-reader-db Error: DB connection failed: SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by zsoro2** [VemtoOrg/vemto2-issues#216]
**Error Message:**
schema-reader-db Error: DB connection failed: SQLSTATE[HY000] [2002] Connection refused

**Stack:**
```
schema-reader-db Error: #0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/src/DatabaseManager.php(20): VemtoDBReader\DatabaseManager->connect()
#1 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(94): VemtoDBReader\DatabaseManager->__construct('mysql')
#2 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#3 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(20): Vemto\Vemto::execute('schema-reader-d...', Object(Closure))
#4 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#5 {main}
```

---

Vemto 2.1.6
darwin 24.1.0
Locale: en-GB
App version: 2.1.6

**Comment by zsoro2** [comment]
<img width="1427" alt="Screenshot 2024-11-25 at 21 37 33" src="https://github.com/user-attachments/assets/d7b64458-49e7-4fc9-9336-f8d120abec22">

**Comment by zsoro2** [comment]
I have an existing project and am trying to use it with Vemto2. My project uses Postgre SQL. 

All I do, I click on the 'Connect Folder' button, I select the specific folder, and then click open. Error appears after. 


Restarting Vemto not helps. It feels like, vemto no picking up my settings from .env file or the config.

**Comment by zsoro2** [comment]
Solved:

Vemto generates a .vemto_settings file and reads the config from there. I had to update my connection there because it was cached.
