### ISSUE TITLE
schema-reader-mg Error: Failed opening required 'D:\xampp\htdocs\test6\bootstrap/../routes/app.php' (include_path='D:\xampp\php\PEAR')

### ISSUE THREAD

**Issue by malekloo-dev** [VemtoOrg/vemto2-issues#217]
**Error Message:**
schema-reader-mg Error: Failed opening required 'D:\xampp\htdocs\test6\bootstrap/../routes/app.php' (include_path='D:\xampp\php\PEAR')

**Stack:**
```
schema-reader-mg Error: #0 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(513): Illuminate\Routing\RouteFileRegistrar->register('D:\\xampp\\htdocs...')
#1 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Routing\Router.php(467): Illuminate\Routing\Router->loadRoutes('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Routing\RouteRegistrar.php(199): Illuminate\Routing\Router->group(Array, 'D:\\xampp\\htdocs...')
#3 D:\xampp\htdocs\test6\bootstrap\app.php(18): Illuminate\Routing\RouteRegistrar->group('D:\\xampp\\htdocs...')
#4 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Foundation\Configuration\ApplicationBuilder.php(257): {closure}(Object(Illuminate\Foundation\Application))
#5 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Illuminate\Foundation\Configuration\ApplicationBuilder->Illuminate\Foundation\Configuration\{closure}()
#6 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Container\Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(83): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#8 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure), Object(Closure))
#9 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Container\Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Object(Closure), Array, NULL)
#10 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(162): Illuminate\Container\Container->call(Object(Closure))
#11 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Foundation\Support\Providers\RouteServiceProvider.php(59): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#12 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Illuminate\Foundation\Support\Providers\RouteServiceProvider->Illuminate\Foundation\Support\Providers\{closure}()
#13 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Container\Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(83): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure), Object(Closure))
#16 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Container\Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Object(Closure), Array, NULL)
#17 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php(144): Illuminate\Container\Container->call(Object(Closure))
#18 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1124): Illuminate\Support\ServiceProvider->callBootedCallbacks()
#19 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1102): Illuminate\Foundation\Application->bootProvider(Object(Illuminate\Foundation\Support\Providers\RouteServiceProvider))
#20 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Illuminate\Foundation\Support\Providers\RouteServiceProvider), 'Illuminate\\Foun...')
#21 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1101): array_walk(Array, Object(Closure))
#22 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#23 D:\xampp\htdocs\test6\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(316): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#24 phar://C:/Users/Netis/AppData/Local/Programs/Vemto/resources/static/VMTTL1/index.php(43): Illuminate\Foundation\Application->bootstrapWith(Array)
#25 phar://C:/Users/Netis/AppData/Local/Programs/Vemto/resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#26 phar://C:/Users/Netis/AppData/Local/Programs/Vemto/resources/static/VMTTL1/index.php(25): Vemto\Vemto::execute('schema-reader-m...', Object(Closure))
#27 C:\Users\Netis\AppData\Local\Programs\Vemto\resources\static\VMTTL1(14): require('phar://C:/Users...')
#28 {main}
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.1.4
win32 10.0.22631
Locale: en-US
App version: 2.1.4

**Comment by TiagoSilvaPereira** [comment]
@malekloo-dev it seems you application is missing the routes/app.php file. Also, please upgrade to Vemto 2.1.6
