### ISSUE TITLE
this.default.replace is not a function

### ISSUE THREAD

**Issue by abdeljalilamd** [VemtoOrg/vemto2-issues#218]
**Error Message:**
this.default.replace is not a function

**Stack:**
```
TypeError: this.default.replace is not a function
    at Proxy.getDefaultForTemplate (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.74b9f7fd.js:115:67634)
    at Object.eval (eval at compileAsync (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.74b9f7fd.js:304:649), <anonymous>:132:25)
    at Nae.compileAsync (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.74b9f7fd.js:304:675)
    at Nae.compileAsyncWithErrorTreatment (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.74b9f7fd.js:304:290)
    at jy.compile (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.74b9f7fd.js:350:14378)
    at jy.compileWithImports (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.74b9f7fd.js:350:13975)
    at async Kpe.generateUpdaterMigration (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.74b9f7fd.js:1161:146511)
    at async Kpe.getContent (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.74b9f7fd.js:1161:145577)
    at async Kpe.getData (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.74b9f7fd.js:1161:144506)
    at async us (file:///Applications/Vemto.app/Contents/Resources/app.asar/renderer/assets/index.74b9f7fd.js:1275:14423)
```

**Template Name:**
```
(anonymous template)
```

**Template Error Line:**
```
102
```

**Template Section:**
```js
100                    <# --- #>
101                    <up if (column.default) { up>
102                    ->default(<$ column.getDefaultForTemplate() $>)
103                    <up } up>
104                    <# --- #>
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.1.6
darwin 23.4.0
Locale: en-US
App version: 2.1.6

**Comment by art35rennes** [comment]
**Error Message:**
this.default.replace is not a function

**Stack:**
```
TypeError: this.default.replace is not a function
    at Proxy.getDefaultForTemplate (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:115:67634)
    at Object.eval (eval at compileAsync (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:304:649), <anonymous>:588:25)
    at Mae.compileAsync (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:304:675)
    at Mae.compileAsyncWithErrorTreatment (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:304:290)
    at jy.compile (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:350:14378)
    at jy.compileWithImports (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:350:13975)
    at async qpe.generateUpdaterMigration (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:1161:146511)
    at async qpe.getContent (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:1161:145577)
    at async qpe.getData (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:1161:144506)
    at async us (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.4d481dca.js:1275:14423)
```

**Template Name:**
```
(anonymous template)
```

**Template Error Line:**
```
420
```

**Template Section:**
```js
418                    <# --- #>
419                    <up if (column.default) { up>
420                    ->default(<$ column.getDefaultForTemplate() $>)
421                    <up } up>
422                    <# --- #>
```

**How to reproduce:**
1. It's seem to be linked to reopen a previous project (previously created with vemto).
2. I delete a model and saved
3. Project had been previously saved with the deleted model

**Expected behavior:**

**Actual behavior:**

**Additional context:**
I have this issue on all my project when i reopen projects and continue to edit models. 

```
Vemto 2.1.6
win32 10.0.22631
Locale: fr
App version: 2.1.6
```

@TiagoSilvaPereira do you have any plan to fix this issue soon ? To generate code i have to recreate project from scratch.

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.1.7
