### ISSUE TITLE
schema-reader-mg Error: Error: config/permission.table_names is empty, did you publish the package configuration?

### ISSUE THREAD

**Issue by maitrepylos** [VemtoOrg/vemto2-issues#219]
**Error Message:**
schema-reader-mg Error: Error: config/permission.table_names is empty, did you publish the package configuration?

**Stack:**
```
schema-reader-mg Error: #0 [internal function]: Illuminate\Database\Migrations\Migration@anonymous->up()
#1 phar:///tmp/.mount_Vemto-5aiCNP/resources/static/VMTTL1/classes/MigrationDecoder.php(22): ReflectionMethod->invoke()
#2 phar:///tmp/.mount_Vemto-5aiCNP/resources/static/VMTTL1/index.php(100): MigrationDecoder->decode()
#3 phar:///tmp/.mount_Vemto-5aiCNP/resources/static/VMTTL1/common/Vemto.php(111): {closure}()
#4 phar:///tmp/.mount_Vemto-5aiCNP/resources/static/VMTTL1/index.php(25): Vemto\Vemto::execute()
#5 /tmp/.mount_Vemto-5aiCNP/resources/static/VMTTL1(15): require('...')
#6 {main}
```

---

Vemto 2.1.6
linux 6.8.0-49-generic
Locale: fr
App version: 2.1.6

**Comment by maitrepylos** [comment]
Sorry, my mistake.
