### ISSUE TITLE
this.default.replace is not a function

### ISSUE THREAD

**Issue by maitrepylos** [VemtoOrg/vemto2-issues#220]
**Error Message:**
this.default.replace is not a function

**Stack:**
```
TypeError: this.default.replace is not a function
    at Proxy.getDefaultForTemplate (file:///tmp/.mount_Vemto-uMq2dj/resources/app.asar/renderer/assets/index.02a5cf45.js:115:67634)
    at Object.eval (eval at compileAsync (file:///tmp/.mount_Vemto-uMq2dj/resources/app.asar/renderer/assets/index.02a5cf45.js:304:649), <anonymous>:132:25)
    at Mae.compileAsync (file:///tmp/.mount_Vemto-uMq2dj/resources/app.asar/renderer/assets/index.02a5cf45.js:304:675)
    at Mae.compileAsyncWithErrorTreatment (file:///tmp/.mount_Vemto-uMq2dj/resources/app.asar/renderer/assets/index.02a5cf45.js:304:290)
    at jy.compile (file:///tmp/.mount_Vemto-uMq2dj/resources/app.asar/renderer/assets/index.02a5cf45.js:350:14378)
    at jy.compileWithImports (file:///tmp/.mount_Vemto-uMq2dj/resources/app.asar/renderer/assets/index.02a5cf45.js:350:13975)
    at async qpe.generateUpdaterMigration (file:///tmp/.mount_Vemto-uMq2dj/resources/app.asar/renderer/assets/index.02a5cf45.js:1161:146511)
    at async qpe.getContent (file:///tmp/.mount_Vemto-uMq2dj/resources/app.asar/renderer/assets/index.02a5cf45.js:1161:145577)
    at async qpe.getData (file:///tmp/.mount_Vemto-uMq2dj/resources/app.asar/renderer/assets/index.02a5cf45.js:1161:144506)
    at async us (file:///tmp/.mount_Vemto-uMq2dj/resources/app.asar/renderer/assets/index.02a5cf45.js:1275:14423)
```

**Template Name:**
```
(anonymous template)
```

**Template Error Line:**
```
102
```

**Template Section:**
```js
100                    <# --- #>
101                    <up if (column.default) { up>
102                    ->default(<$ column.getDefaultForTemplate() $>)
103                    <up } up>
104                    <# --- #>
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.1.6
linux 6.8.0-49-generic
Locale: fr
App version: 2.1.6

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.1.7
