### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by art35rennes** [VemtoOrg/vemto2-issues#221]
**Error Message:**
Cannot read properties of undefined (reading 'toLowerCase')

**Stack:**
```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at sLt.isReserved (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.ebcc0395.js:1160:131402)
    at b (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.ebcc0395.js:1160:134646)
    at y (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.ebcc0395.js:1160:134490)
    at file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.ebcc0395.js:1160:139845
    at Sc.t.<computed>.t.<computed> (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.ebcc0395.js:28:17976)
    at Zv (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.ebcc0395.js:16:2031)
    at Ip (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.ebcc0395.js:16:2102)
    at HTMLDivElement.t (file:///C:/Program%20Files/Vemto/resources/app.asar/renderer/assets/index.ebcc0395.js:28:8321)
```

**How to reproduce:**
1. I created a fresh new project (PostgreSQL, Tailwind, LaravelUI, HasLivewire)
2. A add a new apps called "Blog" and press "enter" or clic "create"

**Expected behavior:**

**Actual behavior:**
First try i pressed enter, nothing happed (stuck in modal) and log window opened with error.
Retype "blog" instead of "Blog" then clic enter and it's work
Delete "blog" and recreate app called "Blog" then clic "create". It's work and error window opened

**Additional context:**

---

Vemto 2.1.3
win32 10.0.22631
Locale: fr
App version: 2.1.3

**Comment by TiagoSilvaPereira** [comment]
This bug was already fixed on more recent Vemto versions. Please upgrade to 2.1.6
