### ISSUE TITLE
schema-reader Error: Class "Livewire\Form" not found

### ISSUE THREAD

**Issue by jonathanjua** [VemtoOrg/vemto2-issues#45]
**Error Message:**
schema-reader Error: Class "Livewire\Form" not found

**Stack:**
```
schema-reader Error: #0 phar://C:/Users/jonathan/AppData/Local/Programs/Vemto/resources/static/VMTTL1/.box/vendor/composer/ClassLoader.php(571): include()
#1 phar://C:/Users/jonathan/AppData/Local/Programs/Vemto/resources/static/VMTTL1/.box/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('C:\\Users\\jonath...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Livewire\\Da...')
#3 phar://C:/Users/jonathan/AppData/Local/Programs/Vemto/resources/static/VMTTL1/classes/ModelRepository.php(296): class_exists('App\\Livewire\\Da...')
#4 [internal function]: ModelRepository::{closure}(Array, 325)
#5 C:\Users\jonathan\Desktop\flow_be\vendor\laravel\framework\src\Illuminate\Collections\Arr.php(830): array_filter(Array, Object(Closure), 1)
#6 C:\Users\jonathan\Desktop\flow_be\vendor\laravel\framework\src\Illuminate\Collections\Collection.php(382): Illuminate\Support\Arr::where(Array, Object(Closure))
#7 phar://C:/Users/jonathan/AppData/Local/Programs/Vemto/resources/static/VMTTL1/classes/ModelRepository.php(306): Illuminate\Support\Collection->filter(Object(Closure))
#8 phar://C:/Users/jonathan/AppData/Local/Programs/Vemto/resources/static/VMTTL1/classes/ModelRepository.php(15): ModelRepository::getModels()
#9 phar://C:/Users/jonathan/AppData/Local/Programs/Vemto/resources/static/VMTTL1/index.php(87): ModelRepository::getModelsFormatted()
#10 phar://C:/Users/jonathan/AppData/Local/Programs/Vemto/resources/static/VMTTL1/common/Vemto.php(107): {closure}()
#11 phar://C:/Users/jonathan/AppData/Local/Programs/Vemto/resources/static/VMTTL1/index.php(93): Vemto::execute('schema-reader', Object(Closure))
#12 C:\Users\jonathan\AppData\Local\Programs\Vemto\resources\static\VMTTL1(14): require('phar://C:/Users...')
#13 {main}
```

---

Vemto 2.0.5
win32 10.0.22631
Locale: pt-BR
App version: 2.0.5

**Comment by TiagoSilvaPereira** [comment]
@jonathanjua is Livewire installed?

**Comment by jonathanjua** [comment]
yes, "livewire/livewire": "^2.11".

**Comment by TiagoSilvaPereira** [comment]
@jonathanjua Vemto 2 CRUD uses Livewire 3... please upgrade the Livewire version
