### ISSUE TITLE
schema-reader Error: Too few arguments to function Faker\Provider\Base::__construct(), 0 passed in /Users/khairulazmi/Desktop/development/mysyarikat/mysyarikatv3/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php on line 978 and exactly 1 expected

### ISSUE THREAD

**Issue by KhairulAzmi21** [VemtoOrg/vemto2-issues#49]
**Error Message:**
schema-reader Error: Too few arguments to function Faker\Provider\Base::__construct(), 0 passed in /Users/khairulazmi/Desktop/development/mysyarikat/mysyarikatv3/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php on line 978 and exactly 1 expected

**Stack:**
```
schema-reader Error: #0 /Users/khairulazmi/Desktop/development/mysyarikat/mysyarikatv3/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(978): Faker\Provider\Base->__construct()
#1 /Users/khairulazmi/Desktop/development/mysyarikat/mysyarikatv3/database/migrations/2024_03_30_065313_create_employee_experiences_table.php(17): Illuminate\Database\Schema\Blueprint->foreignIdFor('Faker\\Provider\\...')
#2 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/classes/ExtendedBuilder.php(21): Illuminate\Database\Migrations\Migration@anonymous->{closure}(Object(ExtendedBlueprint))
#3 /Users/khairulazmi/Desktop/development/mysyarikat/mysyarikatv3/vendor/laravel/framework/src/Illuminate/Support/helpers.php(345): ExtendedBuilder->{closure}(Object(ExtendedBlueprint))
#4 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/classes/ExtendedBuilder.php(18): tap(Object(ExtendedBlueprint), Object(Closure))
#5 /Users/khairulazmi/Desktop/development/mysyarikat/mysyarikatv3/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(357): ExtendedBuilder->create('employee_experi...', Object(Closure))
#6 /Users/khairulazmi/Desktop/development/mysyarikat/mysyarikatv3/database/migrations/2024_03_30_065313_create_employee_experiences_table.php(15): Illuminate\Support\Facades\Facade::__callStatic('create', Array)
#7 [internal function]: Illuminate\Database\Migrations\Migration@anonymous->up()
#8 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/classes/MigrationDecoder.php(22): ReflectionMethod->invoke(Object(Illuminate\Database\Migrations\Migration@anonymous))
#9 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(77): MigrationDecoder->decode()
#10 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/Vemto.php(107): {closure}()
#11 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(18): Vemto::execute('schema-reader', Object(Closure))
#12 /Applications/Vemto.app/Contents/Resources/static/VMTTL1(15): require('phar:///Applica...')
#13 {main}
```

---

Vemto 2.0.3
darwin 23.1.0
Locale: en-US
App version: 2.0.3

**Comment by TiagoSilvaPereira** [comment]
Fixed on 2.0.7 by using the new Database Schema Reader mode
