### ISSUE TITLE
schema-reader Error: Could not create setting general.brand_name because it already exists

### ISSUE THREAD

**Issue by dudungdotnet** [VemtoOrg/vemto2-issues#55]
**Error Message:**
schema-reader Error: Could not create setting general.brand_name because it already exists

**Stack:**
```
schema-reader Error: #0 /Users/dudungdotnet/Projects/PAKAR/pakar-apps-03/vendor/spatie/laravel-settings/src/Migrations/SettingsMigrator.php(54): Spatie\LaravelSettings\Exceptions\SettingAlreadyExists::whenAdding('general.brand_n...')VEMTO_EOL#1 /Users/dudungdotnet/Projects/PAKAR/pakar-apps-03/database/settings/2024_02_20_131300_create_general_settings.php(9): Spatie\LaravelSettings\Migrations\SettingsMigrator->add('general.brand_n...', 'SuperDuper Star...')VEMTO_EOL#2 [internal function]: Spatie\LaravelSettings\Migrations\SettingsMigration@anonymous->up()VEMTO_EOL#3 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/classes/MigrationDecoder.php(22): ReflectionMethod->invoke(Object(Spatie\LaravelSettings\Migrations\SettingsMigration@anonymous))VEMTO_EOL#4 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(77): MigrationDecoder->decode()VEMTO_EOL#5 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/Vemto.php(107): {closure}()VEMTO_EOL#6 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(18): Vemto::execute('schema-reader', Object(Closure))VEMTO_EOL#7 /Applications/Vemto.app/Contents/Resources/static/VMTTL1(15): require('phar:///Applica...')VEMTO_EOL#8 {main}
```

---

Vemto 2.0.6
darwin 23.4.0
Locale: en-US
App version: 2.0.6

**Comment by TiagoSilvaPereira** [comment]
@dudungdotnet is this a new project or an existing one?

**Comment by dudungdotnet** [comment]
Existing project with Plugin Fila Starter Kit

**Comment by TiagoSilvaPereira** [comment]
@dudungdotnet, the current schema reader, has problems with some existing projects. I'm writing a new schema reader (probably coming this week) that can read any project L9+, even if the project includes third-party packages

**Comment by dudungdotnet** [comment]
Great, hopefully it will be finished soon 👍

**Comment by TiagoSilvaPereira** [comment]
@dudungdotnet please try with the new 2.0.7 schema reader (Database mode)
