### ISSUE TITLE
schema-reader Error: Class "Filament\Resources\Resource" not found

### ISSUE THREAD

**Issue by getzleo** [VemtoOrg/vemto2-issues#59]
**Error Message:**
schema-reader Error: Class "Filament\Resources\Resource" not found

**Stack:**
```
#0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/.box/vendor/composer/ClassLoader.php(576): include()VEMTO_EOL#1 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/.box/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/Users/lggil/De...')VEMTO_EOL#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Filament\\Re...')VEMTO_EOL#3 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/classes/ModelRepository.php(296): class_exists('App\\Filament\\Re...')VEMTO_EOL#4 [internal function]: ModelRepository::{closure}(Array, 0)VEMTO_EOL#5 /Users/lggil/Developer/Vemto/fila2/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(925): array_filter(Array, Object(Closure), 1)VEMTO_EOL#6 /Users/lggil/Developer/Vemto/fila2/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(387): Illuminate\Support\Arr::where(Array, Object(Closure))VEMTO_EOL#7 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/classes/ModelRepository.php(293): Illuminate\Support\Collection->filter(Object(Closure))VEMTO_EOL#8 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/classes/ModelRepository.php(15): ModelRepository::getModels()VEMTO_EOL#9 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(87): ModelRepository::getModelsFormatted()VEMTO_EOL#10 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/common/Vemto.php(107): {closure}()VEMTO_EOL#11 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL1/index.php(18): Vemto::execute('schema-reader', Object(Closure))VEMTO_EOL#12 /Applications/Vemto.app/Contents/Resources/static/VMTTL1(15): require('phar:///Applica...')VEMTO_EOL#13 {main}
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.6
darwin 23.4.0
Locale: pt-BR
App version: 2.0.6

**Comment by TiagoSilvaPereira** [comment]
@getzleo is Filament installed?
