### ISSUE TITLE
Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by gdevreese** [VemtoOrg/vemto2-issues#71]
**Error Message:**
Cannot read properties of null (reading 'name')

**Stack:**
```
TypeError: Cannot read properties of null (reading 'name')
    at Object.eval (eval at compileAsync (file:///tmp/.mount_Vemto-SRmm6K/resources/app.asar/renderer/assets/index.9f08d8b1.js:305:649), <anonymous>:250:44)
    at cae.compileAsync (file:///tmp/.mount_Vemto-SRmm6K/resources/app.asar/renderer/assets/index.9f08d8b1.js:305:675)
    at cae.compileAsyncWithErrorTreatment (file:///tmp/.mount_Vemto-SRmm6K/resources/app.asar/renderer/assets/index.9f08d8b1.js:305:290)
    at Oy.compile (file:///tmp/.mount_Vemto-SRmm6K/resources/app.asar/renderer/assets/index.9f08d8b1.js:351:14378)
    at Oy.compileWithImports (file:///tmp/.mount_Vemto-SRmm6K/resources/app.asar/renderer/assets/index.9f08d8b1.js:351:13975)
    at async EP.compile (file:///tmp/.mount_Vemto-SRmm6K/resources/app.asar/renderer/assets/index.9f08d8b1.js:353:3260)
    at async EP.compileWithErrorThreatment (file:///tmp/.mount_Vemto-SRmm6K/resources/app.asar/renderer/assets/index.9f08d8b1.js:353:2381)
    at async zi (file:///tmp/.mount_Vemto-SRmm6K/resources/app.asar/renderer/assets/index.9f08d8b1.js:1251:14426)
    at async Be (file:///tmp/.mount_Vemto-SRmm6K/resources/app.asar/renderer/assets/index.9f08d8b1.js:1251:12203)
    at async Y (file:///tmp/.mount_Vemto-SRmm6K/resources/app.asar/renderer/assets/index.9f08d8b1.js:1251:11296)
```

**Template Error Line:**
```
227
```

**Template Section:**
```

```

**How to reproduce:**
1. Make UI changes
2. Click "Save" on bottom left CTA "There are some schema changes"

**Expected behavior:**
No error, the schema summary is displayed

**Actual behavior:**
An error pops instead

**Additional context:** 
This is a new vemto project. It happened after a few change iterations, when Saving schema changes. There is no obvious conflict or bad relationship. Everything went well until this day where I added about 10 tables w/ different relationships

---

Vemto 2.0.6
linux 6.5.0-27-generic
Locale: fr
App version: 2.0.6

**Comment by TiagoSilvaPereira** [comment]
Hi @gdevreese could you please try if 2.0.7 fixes this issue?

**Comment by gdevreese** [comment]
hi @TiagoSilvaPereira 
I still have the same issue with 2.0.7
Maybe there is an error in my schema but I cannot see it

**Error Message:**
Cannot read properties of null (reading 'name')

**Stack:**
```
TypeError: Cannot read properties of null (reading 'name')
    at Object.eval (eval at compileAsync (file:///tmp/.mount_Vemto-SHgzVS/resources/app.asar/renderer/assets/index.afb781ea.js:315:649), <anonymous>:250:44)
    at Dae.compileAsync (file:///tmp/.mount_Vemto-SHgzVS/resources/app.asar/renderer/assets/index.afb781ea.js:315:675)
    at Dae.compileAsyncWithErrorTreatment (file:///tmp/.mount_Vemto-SHgzVS/resources/app.asar/renderer/assets/index.afb781ea.js:315:290)
    at Vy.compile (file:///tmp/.mount_Vemto-SHgzVS/resources/app.asar/renderer/assets/index.afb781ea.js:361:14378)
    at Vy.compileWithImports (file:///tmp/.mount_Vemto-SHgzVS/resources/app.asar/renderer/assets/index.afb781ea.js:361:13975)
    at async IR.compile (file:///tmp/.mount_Vemto-SHgzVS/resources/app.asar/renderer/assets/index.afb781ea.js:363:4479)
    at async IR.compileWithErrorThreatment (file:///tmp/.mount_Vemto-SHgzVS/resources/app.asar/renderer/assets/index.afb781ea.js:363:3600)
    at async xi (file:///tmp/.mount_Vemto-SHgzVS/resources/app.asar/renderer/assets/index.afb781ea.js:1261:14426)
    at async Pe (file:///tmp/.mount_Vemto-SHgzVS/resources/app.asar/renderer/assets/index.afb781ea.js:1261:12203)
    at async Y (file:///tmp/.mount_Vemto-SHgzVS/resources/app.asar/renderer/assets/index.afb781ea.js:1261:11296)
```

**Template Error Line:**
```
227
```

**Template Section:**
```

```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.7
linux 6.5.0-27-generic
Locale: fr
App version: 2.0.7

**Comment by TiagoSilvaPereira** [comment]
@gdevreese is it a private project? Would you ming to share a git repository where we can reproduce that?

**Comment by gdevreese** [comment]
@TiagoSilvaPereira yes it is a private project. 
I just sent you a guest invite

**Comment by TiagoSilvaPereira** [comment]
Hi @gdevreese sorry I did not have time to look at your project yet. Would it be possible to try to replicate the error and record a video?

**Comment by TiagoSilvaPereira** [comment]
Hi @gdevreese, could you please try to send the report on this issue again? Vemto 2.0.10 has better error reporting, and this will help me find what is happening here

**Comment by TiagoSilvaPereira** [comment]
Related to https://github.com/TiagoSilvaPereira/vemto2-issues/issues/127

![image](https://github.com/TiagoSilvaPereira/vemto2-issues/assets/11933789/c2a3c0ee-0fba-47f7-9290-44f8ee070b1f)

**Comment by TiagoSilvaPereira** [comment]
@gdevreese sorry for the long wait, I finally managed to fix this bug. This problem was caused by some flaws in the Schema architecture (caused by invalid relationships) that I managed to improve in the last two versions.

Best regards
