### ISSUE TITLE
Cannot drop column 'ranking_id': needed in a foreign key constraint 'competicoes_ranking_id_foreign'

### ISSUE THREAD

**Issue by kinzinho666** [VemtoOrg/vemto2-issues#75]
**Error Message:**
schema-reader Error: SQLSTATE[HY000]: General error: 1828 Cannot drop column 'ranking_id': needed in a foreign key constraint 'competicoes_ranking_id_foreign' (Connection: vemto_db_connection, SQL: alter table `competicoes` drop `ranking_id`)

**Stack:**
```
#0 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Connection.php(767): Illuminate\Database\Connection->runQueryCallback('alter table `co...', Array, Object(Closure))VEMTO_EOL#1 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Connection.php(560): Illuminate\Database\Connection->run('alter table `co...', Array, Object(Closure))VEMTO_EOL#2 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php(109): Illuminate\Database\Connection->statement('alter table `co...')VEMTO_EOL#3 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(564): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))VEMTO_EOL#4 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(406): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))VEMTO_EOL#5 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(357): Illuminate\Database\Schema\Builder->table('competicoes', Object(Closure))VEMTO_EOL#6 C:\laragon\www\np2\RK\database\migrations\2024_04_15_230233_001_update_competicoes_table.php(15): Illuminate\Support\Facades\Facade::__callStatic('table', Array)VEMTO_EOL#7 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(482): Illuminate\Database\Migrations\Migration@anonymous->up()VEMTO_EOL#8 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(408): Illuminate\Database\Migrations\Migrator->runMethod(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')VEMTO_EOL#9 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(417): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()VEMTO_EOL#10 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(214): Illuminate\Database\Migrations\Migrator->runMigration(Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')VEMTO_EOL#11 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(749): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()VEMTO_EOL#12 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(214): Illuminate\Database\Migrations\Migrator->write('Illuminate\\Cons...', '2024_04_15_2302...', Object(Closure))VEMTO_EOL#13 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(179): Illuminate\Database\Migrations\Migrator->runUp('C:\\laragon\\www\\...', 1, false)VEMTO_EOL#14 C:\laragon\www\np2\RK\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(122): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)VEMTO_EOL#15 phar://C:/Users/k1/AppData/Local/Programs/vemto/resources/static/VMTTL2/index.php(103): Illuminate\Database\Migrations\Migrator->run('C:\\laragon\\www\\...')VEMTO_EOL#16 phar://C:/Users/k1/AppData/Local/Programs/vemto/resources/static/VMTTL2/common/Vemto.php(111): {closure}()VEMTO_EOL#17 phar://C:/Users/k1/AppData/Local/Programs/vemto/resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute('schema-reader', Object(Closure))VEMTO_EOL#18 C:\Users\k1\AppData\Local\Programs\vemto\resources\static\VMTTL2(14): require('phar://C:/Users...')VEMTO_EOL#19 {main}
```

**How to reproduce:**
1.  Criei as tabelas
2.  criei relacionamentos, salvei e foi criado as migrations
3. removi as relações 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.7
win32 10.0.22631
Locale: pt-BR
App version: 2.0.7

**Comment by TiagoSilvaPereira** [comment]
@kinzinho666 seems Vemto dropped a column without dropping the foreign key. For now you can fix your migrations and sync the code. We'll fix it in upcoming versions

**Comment by TiagoSilvaPereira** [comment]
Fixed
