### ISSUE TITLE
schema-reader Error: SQLSTATE[HY000]: General error: 1824 Failed to open the referenced table 'Center' (Connection: vemto_db_connection, SQL: alter table `users` add constraint `users_center_id_foreign` foreign key (`center_id`) references `Center` (`id`) on delete cascade on update cascade)

### ISSUE THREAD

**Issue by turkialawlqy** [VemtoOrg/vemto2-issues#82]
**Error Message:**
schema-reader Error: SQLSTATE[HY000]: General error: 1824 Failed to open the referenced table 'Center' (Connection: vemto_db_connection, SQL: alter table `users` add constraint `users_center_id_foreign` foreign key (`center_id`) references `Center` (`id`) on delete cascade on update cascade)

**Stack:**
```
#0 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(767): Illuminate\Database\Connection->runQueryCallback('alter table `us...', Array, Object(Closure))VEMTO_EOL#1 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(560): Illuminate\Database\Connection->run('alter table `us...', Array, Object(Closure))VEMTO_EOL#2 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(109): Illuminate\Database\Connection->statement('alter table `us...')VEMTO_EOL#3 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))VEMTO_EOL#4 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(406): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))VEMTO_EOL#5 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(357): Illuminate\Database\Schema\Builder->table('users', Object(Closure))VEMTO_EOL#6 /Users/turkialawlqy/Herd/t-shabwah1/database/migrations/2024_04_16_201327_add_two_factor_columns_to_users_table.php(14): Illuminate\Support\Facades\Facade::__callStatic('table', Array)VEMTO_EOL#7 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(482): Illuminate\Database\Migrations\Migration@anonymous->up()VEMTO_EOL#8 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(408): Illuminate\Database\Migrations\Migrator->runMethod(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')VEMTO_EOL#9 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(417): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()VEMTO_EOL#10 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(214): Illuminate\Database\Migrations\Migrator->runMigration(Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')VEMTO_EOL#11 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(749): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()VEMTO_EOL#12 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(214): Illuminate\Database\Migrations\Migrator->write('Illuminate\\Cons...', '2024_04_16_2013...', Object(Closure))VEMTO_EOL#13 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(179): Illuminate\Database\Migrations\Migrator->runUp('/Users/turkiala...', 1, false)VEMTO_EOL#14 /Users/turkialawlqy/Herd/t-shabwah1/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(122): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)VEMTO_EOL#15 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(103): Illuminate\Database\Migrations\Migrator->run('/Users/turkiala...')VEMTO_EOL#16 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()VEMTO_EOL#17 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute('schema-reader', Object(Closure))VEMTO_EOL#18 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')VEMTO_EOL#19 {main}
```

**How to reproduce:**
1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Additional context:**

---

Vemto 2.0.7
darwin 23.4.0
Locale: en-US
App version: 2.0.7

**Comment by TiagoSilvaPereira** [comment]
@turkialawlqy, could you please check if this error occurs when you run your migrations manually?

**Comment by TiagoSilvaPereira** [comment]
Closing due to the lack of details. Please feel free to reopen
