### ISSUE TITLE
schema-reader Error

### ISSUE THREAD

**Issue by LeonardoPessatti** [VemtoOrg/vemto2-issues#84]
It happens while trying to connect a folder. 
Already tried to delete .vemto folder and settings in project and deleted Vemto folders in system.
Even after removing everything, it still remembers the database connection details.

**Error Message:**
schema-reader Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Array) not null, `created_at` timestamp null, `updated_at` timestamp null, `user' at line 1 (Connection: vemto_db_connection, SQL: create table `universes` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `history` varchar(255) null, `map` varchar(255) null, `theme` varchar(Array) not null, `created_at` timestamp null, `updated_at` timestamp null, `user_id` bigint unsigned not null))

**Stack:**
```
schema-reader Error: #0 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Connection.php(767): Illuminate\Database\Connection->runQueryCallback('create table `u...', Array, Object(Closure))
#1 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Connection.php(560): Illuminate\Database\Connection->run('create table `u...', Array, Object(Closure))
#2 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Schema\Blueprint.php(109): Illuminate\Database\Connection->statement('create table `u...')
#3 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(564): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Schema\Builder.php(418): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(357): Illuminate\Database\Schema\Builder->create('universes', Object(Closure))
#6 C:\wamp64\www\Epic Brew\database\migrations\2024_04_15_190321_001_create_universes_table.php(15): Illuminate\Support\Facades\Facade::__callStatic('create', Array)
#7 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(482): Illuminate\Database\Migrations\Migration@anonymous->up()
#8 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(408): Illuminate\Database\Migrations\Migrator->runMethod(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')
#9 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(417): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#10 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(214): Illuminate\Database\Migrations\Migrator->runMigration(Object(Illuminate\Database\Migrations\Migration@anonymous), 'up')
#11 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(749): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#12 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(214): Illuminate\Database\Migrations\Migrator->write('Illuminate\\Cons...', '2024_04_15_1903...', Object(Closure))
#13 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(179): Illuminate\Database\Migrations\Migrator->runUp('C:\\wamp64\\www\\E...', 1, false)
#14 C:\wamp64\www\Epic Brew\vendor\laravel\framework\src\Illuminate\Database\Migrations\Migrator.php(122): Illuminate\Database\Migrations\Migrator->runPending(Array, Array)
#15 phar://C:/Program Files/Vemto/resources/static/VMTTL2/index.php(103): Illuminate\Database\Migrations\Migrator->run('C:\\wamp64\\www\\E...')
#16 phar://C:/Program Files/Vemto/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#17 phar://C:/Program Files/Vemto/resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute('schema-reader', Object(Closure))
#18 C:\Program Files\Vemto\resources\static\VMTTL2(14): require('phar://C:/Progr...')
#19 {main}
```

---

Vemto 2.0.7
win32 10.0.22621
Locale: pt-BR
App version: 2.0.7

**Comment by TiagoSilvaPereira** [comment]
Hi, @LeonardoPessatti. Are the migrations from this project running normally? The error message shows there are errors in SQL syntax when trying to run migrations (Vemto needs to run the migrations before reading the schema structure). I recommend trying to run the migrations manually to check what is happening

**Comment by LeonardoPessatti** [comment]
I will run migrations manually when I arrive home, but they were generated by Vemto.
Also, does Vemto run the migrations when connecting to the project folder?

**Comment by TiagoSilvaPereira** [comment]
No, Vemto only generates migrations when you save them from the Schema Designer. If you didn't save any migration, there are only the migrations generated by a new Laravel installation in the project folder

**Comment by TiagoSilvaPereira** [comment]
@LeonardoPessatti did you manage to test the migrations? Maybe there is some problem in the migrations code?

**Comment by LeonardoPessatti** [comment]
Yes, deleted the migrations and the problem disappeared.
