### ISSUE TITLE
schema-reader Error: DB connection failed: could not find driver

### ISSUE THREAD

**Issue by turkialawlqy** [VemtoOrg/vemto2-issues#91]
**Error Message:**
schema-reader Error: DB connection failed: could not find driver

**Stack:**
```
schema-reader Error: #0 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/src/DatabaseManager.php(20): VemtoDBReader\DatabaseManager->connect()
#1 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(77): VemtoDBReader\DatabaseManager->__construct('mariadb')
#2 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#3 phar:///Applications/Vemto.app/Contents/Resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute('schema-reader', Object(Closure))
#4 /Applications/Vemto.app/Contents/Resources/static/VMTTL2(15): require('phar:///Applica...')
#5 {main}
```

---

Vemto 2.0.8
darwin 23.4.0
Locale: en-US
App version: 2.0.8

**Comment by TiagoSilvaPereira** [comment]
Hi @turkialawlqy, I'll close this as it does not seem to be a Vemto issue. Seems you need to enable the PDO mariadb driver on your PHP configuration.
