### ISSUE TITLE
Database - Read from database (Unknown Error)

### ISSUE THREAD

**Issue by slzno** [VemtoOrg/vemto2-issues#98]
**Error Message:**
Unknown Error

**Stack:**
```
schema-reader Error: #0 phar:///tmp/.mount_vemto-bPA8Fy/resources/static/VMTTL2/index.php(80): VemtoDBReader\DatabaseManager->dropDatabase()
#1 phar:///tmp/.mount_vemto-bPA8Fy/resources/static/VMTTL2/common/Vemto.php(111): {closure}()
#2 phar:///tmp/.mount_vemto-bPA8Fy/resources/static/VMTTL2/index.php(18): Vemto\Vemto::execute()
#3 /tmp/.mount_vemto-bPA8Fy/resources/static/VMTTL2(15): require('...')
#4 {main}
```

---

Vemto 2.0.8
linux 6.8.0-76060800daily20240311-generic
Locale: en-US
App version: 2.0.8

**Comment by TiagoSilvaPereira** [comment]
@ldavidsp please check Vemto 2.0.10. Please feel free to reopen if necessary
